<?php


/**
 * Implementation of hook_ctools_plugin_api().
 */
function os_boxes_ctools_plugin_api($module, $api) {
  if ($module == 'boxes' && $api == 'plugins') {
    return array('version' => 1);
  }
}

/**
 * Implementation of hook_boxes_plugins().
 */
function os_boxes_boxes_plugins() {
  $info = array();
  $info['os_boxes_default'] = array(
    'title' => '', 
    'handler' => array(
      'class' => 'os_boxes_default',
      'file' => 'os_boxes_default.inc',
      'path' => drupal_get_path('module', 'os_boxes') .'/boxes',
      'parent' => 'box',
    ),
  );
  $info['os_boxes_list'] = array(
    'title' => 'Listing',  // i.e. view
    'handler' => array(
      'class' => 'os_boxes_list',
      'file' => 'os_boxes_list.inc',
      'path' => drupal_get_path('module', 'os_boxes') .'/boxes',
      'parent' => 'os_boxes_default',
    ),
  );

  return $info;
}
